name: ARC Firmware

on: [push, pull_request]

jobs:
  arcldr:
    name: ARC Firmware loader
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v4

    - name: Build ARC Firmware loader
      run: |
        cd arcldr
        make -f Makefile.wii
        make -f Makefile.gc

    - uses: actions/upload-artifact@v4
      with:
        path: arcldr_*.dol
    
  baselibc:
    name: libc
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v4
        
    - name: Build little endian libc
      run: |
        cd arcfw/baselibc
        make

  arcfw:
    name: ARC firmware
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    needs: baselibc
 
    steps:
    - uses: actions/checkout@v4
        
    - name: Install zstd
      run: |
        apt-get -y install zstd
    - name: Download libc
      run: |
        cd ..
        wget https://repo-de.voidlinux.org/current/cross-powerpcle-linux-gnu-0.34_1.x86_64.xbps
        zstdcat cross-powerpcle-linux-gnu-0.34_1.x86_64.xbps -o cross-powerpcle-linux-gnu-0.34_1.x86_64.tar
        tar -xf cross-powerpcle-linux-gnu-0.34_1.x86_64.tar
        cp usr/lib/gcc/powerpcle-linux-gnu/10.2/libgcc.a entii-for-workcubes/arcfw/gccle/
    - name: Build ARC Firmware
      run: |
        cd arcfw
        mkdir build
        make
